# -*- coding: utf-8 -*-
"""
Created on Tue Jan  5 13:53:56 2021

@author: zefyr

This script can be used to take a bunch of photos quickly for our ML training
of arrow recognition. Put a copy of the script in a new directory (or change
the filepaths), and create the following folders in that directory:
    left
    right
    up
    down
    else
These folders are NOT autogenerated, to ensure photos aren't generated in your
local Github repository due to running the script in that directory in error.

When you run the script, you are given a video feed. Point your printed arrow
in a direction and use the appropriate key to indicate the pointed direction:
    w - up
    s - down
    a - your left (computer right)
    d - your right (computer left)
    e - any other direction, back of the card, or lack of arrow entirely

Do this as many times as you would like, and then quit:
    q - quit
"""

import numpy as np
import cv2
import datetime

cap = cv2.VideoCapture(0)

while(True):
    # Capture frame-by-frame
    ret, frame = cap.read()
    frame = cv2.flip(frame,1)

    # Display the resulting frame
    cv2.imshow('frame',frame)
    k = cv2.waitKey(1)
    if k & 0xFF == ord('q'):
        break
    elif k == ord('a'): # point right (flipped from left)
        curr = datetime.datetime.now()
        cv2.imwrite('right/' + curr.strftime("%M%S%f") + '.png',frame)
    elif k == ord('d'): # point left (flipped from right)
        curr = datetime.datetime.now()
        cv2.imwrite('left/' + curr.strftime("%M%S%f") + '.png',frame)
    elif k == ord('w'): # point up
        curr = datetime.datetime.now()
        cv2.imwrite('up/' + curr.strftime("%M%S%f") + '.png',frame)
    elif k == ord('s'): # point down
        curr = datetime.datetime.now()
        cv2.imwrite('down/' + curr.strftime("%M%S%f") + '.png',frame)
    elif k == ord('e'): # point else
        curr = datetime.datetime.now()
        cv2.imwrite('else/' + curr.strftime("%M%S%f") + '.png',frame)

# When everything done, release the capture
cap.release()
cv2.destroyAllWindows()